// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.AspNetCore.Builder;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.ML;
using Microsoft.OpenApi.Models;
using Microsoft.ML.Data;
using System.Drawing;
using System.IO;
using System.Threading.Tasks;

// Configure app
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddPredictionEnginePool<MLImageClassification.ModelInput, MLImageClassification.ModelOutput>()
    .FromFile("MLImageClassification.mlnet");

builder.Services.AddEndpointsApiExplorer();

builder.Services.AddSwaggerGen(c =>
{
    c.SwaggerDoc("v1", new OpenApiInfo { Title = "My API", Description = "Docs for my API", Version = "v1" });
});

var app = builder.Build();

// Serve Swagger UI at application root ("/")
app.UseSwagger();
app.UseSwaggerUI(c =>
{
    c.SwaggerEndpoint("/swagger/v1/swagger.json", "My API V1");
    c.RoutePrefix = string.Empty; // serve Swagger UI at "/"
});

// Optional: redirect root to swagger (safe fallback)
app.MapGet("/", () => Results.Redirect("/"));


// Define prediction route & handler
app.MapPost("/predict",
    async (PredictionEnginePool<MLImageClassification.ModelInput, MLImageClassification.ModelOutput> predictionEnginePool, string imagePath) =>
    {
        var input = new MLImageClassification.ModelInput()
        {
            ImageSource = File.ReadAllBytes(imagePath),
        };

        return await Task.FromResult(predictionEnginePool.Predict(input));
    });

// Run app
app.Run();
