
// This file was auto-generated by ML.NET Model Builder. 

using MLImageClassification_ConsoleApp;
using System.IO;

// Create single instance of sample data from first line of dataset for model input
var imageBytes = File.ReadAllBytes(@"C:\Users\AdrianKrześniak\source\repos\MLImageClassification\MLImageClassification\DataSet\flower_photos\daisy\100080576_f52e8ee070_n.jpg");
MLImageClassification.ModelInput sampleData = new MLImageClassification.ModelInput()
{
    ImageSource = imageBytes,
};

// Make a single prediction on the sample data and print results.
var sortedScoresWithLabel = MLImageClassification.PredictAllLabels(sampleData);
Console.WriteLine($"{"Class",-40}{"Score",-20}");
Console.WriteLine($"{"-----",-40}{"-----",-20}");

foreach (var score in sortedScoresWithLabel)
{
    Console.WriteLine($"{score.Key,-40}{score.Value,-20}");
}
